version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pokedyn
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pokedyn_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "L32VssW-R7PHDYU9wLUcEp4QSJuXjs-d"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  pokedyn_data:
